import { getLang } from '../../side/i18n';

const sv = {
  collection: 'SPEL FRÅN RINGSTORP', choose: 'Vad vill du spela?',
  intro: 'Två världar. Nya äventyr precis runt hörnet.',
  ringstorp: 'Ringstorp Run', runTag: 'ARKADÄVENTYR · 4 BANOR',
  runDescription: 'Paket, hemliga uppdrag och en långtur i Karlstad. Ta den gula bussen hem till Liljedal.',
  runAction: 'Välj bana', carl: 'Carl-Ottos spel', carlTag: 'SMÅ ÄVENTYR · STOR UPPTÄCKARLUST',
  carlDescription: 'På med den blå hjälmen! Cykla till förskolan, lek kurragömma med kompisarna och gör filmkväll hemma.',
  carlAction: 'Upptäck spelen', back: 'Alla spel', first: 'SPEL 1',
  bikeTitle: 'Till förskolan', bikeDescription: 'Det är en fin morgon i Höganäs. Hjälp Carl-Otto att cykla till den röda förskolan och väja för äpplena som faller från träden.',
  bikeInstructions: 'Cykeln rullar av sig själv. Styr med piltangenterna eller WASD. På en pekskärm använder du pilknapparna.',
  bikeHint: 'Titta efter ringarna på marken – där faller nästa äpple!',
  start: 'Börja cykla', pause: 'Pausa', resume: 'Fortsätt cykla', again: 'Cykla igen',
  paused: 'En liten paus', pausedBody: 'Cykeln väntar här tills du är redo.',
  won: 'Framme vid förskolan!', wonBody: 'Bra cyklat, Carl-Otto! Parkera cykeln – nu väntar en dag med lek.',
  lost: 'Hoppsan, ett äpple!', lostBody: 'Vi tar en ny cykeltur! Håll utkik efter ringarna på marken och styr undan.',
  home: 'Hemma', preschool: 'Förskolan', left: 'm kvar', hearts: 'Hjärtan', avoided: 'äpplen undvikna',
  steer: 'STYR', pauseHint: 'ESC · PAUS     M · LJUD', soundOn: 'Ljud: på', soundOff: 'Ljud: av', up: 'Styr uppåt', down: 'Styr nedåt',
  moveLeft: 'Styr åt vänster', moveRight: 'Styr åt höger',
  footer: 'SMÅ ÄVENTYR I HELSINGBORG, HÖGANÄS OCH KARLSTAD', menu: 'Välj spel',
  second: 'SPEL 2', hideTitle: 'Kurragömma',
  bikeBlurb: 'Cykla till förskolan och väj för äpplena som faller.', hideBlurb: 'Hitta alla fem kompisar på förskolans gård.',
  hideDescription: 'Kompisarna har gömt sig på förskolans gård. Kan Carl-Otto hitta alla fem? De är inte så bra på att gömma sig…',
  hideInstructions: 'Gå med piltangenterna eller A och D. Tryck mellanslag vid ett gömställe för att titta. På en pekskärm trycker du där du vill titta.',
  hideHint: 'Lyssna efter fnitter – och titta efter fötter som sticker ut!',
  countStart: 'Börja räkna', skipCount: 'MELLANSLAG · SLUTA RÄKNA', here: 'Nu kommer jag!', look: 'Titta!', hihi: 'hihi!',
  foundAll: 'Du hittade alla!', foundAllBody: 'Alla kompisar är hittade. Bra letat, Carl-Otto!', tookTime: 'Det tog {time}.',
  seekAgain: 'Leta igen', foundStatus: '{name} hittad! {n} kvar.', foundLast: '{name} hittad! Alla är hittade!',
  friends: 'KOMPISAR', seekKeys: 'GÅ ◀ ▶ / A D     TITTA · MELLANSLAG     ESC · PAUS     M · LJUD', hidePaused: 'Paus i leken',
  hidePausedBody: 'Kompisarna väntar i sina gömställen.',
  third: 'SPEL 3', movieTitle: 'Filmkväll', movieBlurb: 'Hitta det som behövs till filmkvällen och gör soffan mysig.',
  movieInstructions: 'Det är filmkväll! Hitta filten, kudden, nallen, popcornen och fjärrkontrollen och bär dem till soffan. Gå med piltangenterna eller A och D och tryck mellanslag för att titta. På en pekskärm trycker du där du vill titta.',
  movieHint: 'Titta efter något som sticker fram – en filtflik eller ett nalleöra!',
  movieStart: 'Börja leta', toSofa: 'TILL SOFFAN', foundItem: '{name} hittad! Bär den till soffan.',
  placedItem: '{name} ligger i soffan. {n} kvar.', placedLast: '{name} ligger i soffan. Allt är klart!', filmStarts: 'Nu börjar filmen!',
  movieDone: 'Filmen börjar!', movieDoneBody: 'Vilken mysig soffa, Carl-Otto! Nu är det filmkväll.', lookAgain: 'Leta igen',
  moviePaused: 'Paus i filmkvällen', moviePausedBody: 'Allt ligger kvar där det är.',
};

const en: Record<keyof typeof sv, string> = {
  collection: 'GAMES FROM RINGSTORP', choose: 'What shall we play?', intro: 'Two worlds. New adventures just around the corner.',
  ringstorp: 'Ringstorp Run', runTag: 'ARCADE ADVENTURES · 4 LEVELS',
  runDescription: 'Parcels, secret assignments and a long run through Karlstad. Take the yellow bus home to Liljedal.', runAction: 'Choose a level',
  carl: 'Carl-Ottos spel', carlTag: 'LITTLE ADVENTURES · BIG CURIOSITY',
  carlDescription: 'Blue helmet on! Ride to preschool, play hide and seek with friends, and get ready for movie night at home.', carlAction: 'Explore the games',
  back: 'All games', first: 'GAME 1', bikeTitle: 'Off to preschool',
  bikeDescription: 'It’s a lovely morning in Höganäs. Help Carl-Otto cycle to the red preschool and dodge the apples falling from the trees.',
  bikeInstructions: 'The bike rolls along by itself. Steer with the arrow keys or WASD. On a touchscreen, use the arrow buttons.',
  bikeHint: 'Watch the rings on the ground – that’s where the next apple will fall!',
  start: 'Start cycling', pause: 'Pause', resume: 'Keep cycling', again: 'Ride again',
  paused: 'A little break', pausedBody: 'Your bike will wait here until you’re ready.',
  won: 'You made it to preschool!', wonBody: 'Well done, Carl-Otto! Park your bike – a day of play is waiting.',
  lost: 'Oops, an apple!', lostBody: 'Let’s try another ride! Watch the rings on the ground and steer clear.',
  home: 'Home', preschool: 'Preschool', left: 'm left', hearts: 'Hearts', avoided: 'apples avoided',
  steer: 'STEER', pauseHint: 'ESC · PAUSE     M · SOUND', soundOn: 'Sound: on', soundOff: 'Sound: off', up: 'Steer up', down: 'Steer down', moveLeft: 'Steer left', moveRight: 'Steer right',
  footer: 'LITTLE ADVENTURES IN HELSINGBORG, HÖGANÄS AND KARLSTAD', menu: 'Choose a game',
  second: 'GAME 2', hideTitle: 'Hide and seek',
  bikeBlurb: 'Ride to preschool and dodge the falling apples.', hideBlurb: 'Find all five friends in the preschool yard.',
  hideDescription: 'The friends are hiding in the preschool yard. Can Carl-Otto find all five? They’re not very good at hiding…',
  hideInstructions: 'Walk with the arrow keys or A and D. Press space at a hiding place to look. On a touchscreen, tap where you want to look.',
  hideHint: 'Listen for giggles – and look out for feet sticking out!',
  countStart: 'Start counting', skipCount: 'SPACE · STOP COUNTING', here: 'Ready or not, here I come!', look: 'Look!', hihi: 'hee hee!',
  foundAll: 'You found everyone!', foundAllBody: 'All the friends are found. Great seeking, Carl-Otto!', tookTime: 'It took {time}.',
  seekAgain: 'Play again', foundStatus: '{name} found! {n} to go.', foundLast: '{name} found! Everyone is found!',
  friends: 'FRIENDS', seekKeys: 'WALK ◀ ▶ / A D     LOOK · SPACE     ESC · PAUSE     M · SOUND', hidePaused: 'A little break',
  hidePausedBody: 'Your friends are waiting in their hiding places.',
  third: 'GAME 3', movieTitle: 'Movie night', movieBlurb: 'Find what movie night needs and make the sofa cosy.',
  movieInstructions: 'It’s movie night! Find the blanket, the cushion, Teddy, the popcorn and the remote, and carry them to the sofa. Walk with the arrow keys or A and D, and press space to look. On a touchscreen, tap where you want to look.',
  movieHint: 'Look out for something poking out – a corner of the blanket or a teddy ear!',
  movieStart: 'Start looking', toSofa: 'FOR THE SOFA', foundItem: 'Found {name}! Carry it to the sofa.',
  placedItem: 'On the sofa: {name}. {n} to go.', placedLast: 'On the sofa: {name}. Everything’s ready!', filmStarts: 'The film is starting!',
  movieDone: 'The film is on!', movieDoneBody: 'What a cosy sofa, Carl-Otto! Movie night can begin.', lookAgain: 'Play again',
  moviePaused: 'A little break', moviePausedBody: 'Everything stays right where it is.',
};

export const familyText = (key: keyof typeof sv): string => (getLang() === 'sv' ? sv : en)[key];
