import { getLang } from '../../side/i18n';

const sv = {
  collection: 'SPEL FRÅN RINGSTORP', choose: 'Vad vill du spela?',
  intro: 'Två världar. Nya äventyr precis runt hörnet.',
  ringstorp: 'Ringstorp Run', runTag: 'ARKADÄVENTYR · 4 BANOR',
  runDescription: 'Paket, hemliga uppdrag och en långtur i Karlstad. Ta den gula bussen hem till Liljedal.',
  runAction: 'Välj bana', carl: 'Carl-Ottos spel', carlTag: 'SMÅ ÄVENTYR · STOR UPPTÄCKARLUST',
  carlDescription: 'På med den blå hjälmen! Cykla till förskolan, lek kurragömma med kompisarna och gör filmkväll hemma.',
  carlAction: 'Upptäck spelen', back: 'Alla spel', first: 'SPEL 1',
  bikeTitle: 'Till förskolan', bikeDescription: 'Det är en fin morgon i Höganäs. Hjälp Carl-Otto att cykla till den röda förskolan och väja för äpplena som faller från träden.',
  bikeInstructions: 'Cykeln rullar av sig själv. Styr med piltangenterna eller WASD. På en pekskärm använder du pilknapparna.',
  bikeHint: 'Titta efter ringarna på marken – där faller nästa äpple!',
  start: 'Börja cykla', pause: 'Pausa', resume: 'Fortsätt cykla', again: 'Cykla igen',
  paused: 'En liten paus', pausedBody: 'Cykeln väntar här tills du är redo.',
  won: 'Framme vid förskolan!', wonBody: 'Bra cyklat, Carl-Otto! Parkera cykeln – nu väntar en dag med lek.',
  lost: 'Hoppsan, ett äpple!', lostBody: 'Vi tar en ny cykeltur! Håll utkik efter ringarna på marken och styr undan.',
  home: 'Hemma', preschool: 'Förskolan', left: 'm kvar', hearts: 'Hjärtan', avoided: 'äpplen undvikna',
  steer: 'STYR', pauseHint: 'ESC · PAUS     M · LJUD', soundOn: 'Ljud: på', soundOff: 'Ljud: av', up: 'Styr uppåt', down: 'Styr nedåt',
  moveLeft: 'Styr åt vänster', moveRight: 'Styr åt höger',
  footer: 'SMÅ ÄVENTYR I HELSINGBORG, HÖGANÄS OCH KARLSTAD', menu: 'Välj spel',
  second: 'SPEL 2', hideTitle: 'Kurragömma',
  bikeBlurb: 'Cykla till förskolan och väj för äpplena som faller.', hideBlurb: 'Hitta alla fem kompisar på förskolans gård.',
  hideDescription: 'Kompisarna har gömt sig på förskolans gård. Kan Carl-Otto hitta alla fem? De är inte så bra på att gömma sig…',
  hideInstructions: 'Gå med piltangenterna eller A och D. Tryck mellanslag vid ett gömställe för att titta. På en pekskärm trycker du där du vill titta.',
  hideHint: 'Lyssna efter fnitter – och titta efter fötter som sticker ut!',
  countStart: 'Börja räkna', skipCount: 'MELLANSLAG · SLUTA RÄKNA', here: 'Nu kommer jag!', look: 'Titta!', hihi: 'hihi!',
  foundAll: 'Du hittade alla!', foundAllBody: 'Alla kompisar är hittade. Bra letat, Carl-Otto!', tookTime: 'Det tog {time}.',
  seekAgain: 'Leta igen', foundStatus: '{name} hittad! {n} kvar.', foundLast: '{name} hittad! Alla är hittade!',
  friends: 'KOMPISAR', seekKeys: 'GÅ ◀ ▶ / A D     TITTA · MELLANSLAG     ESC · PAUS     M · LJUD', hidePaused: 'Paus i leken',
  hidePausedBody: 'Kompisarna väntar i sina gömställen.',
  third: 'SPEL 3', movieTitle: 'Filmkväll', movieBlurb: 'Hitta det som behövs till filmkvällen och gör soffan mysig.',
  movieInstructions: 'Det är filmkväll! Hitta filten, kudden, nallen, popcornen och fjärrkontrollen och bär dem till soffan. Gå med piltangenterna eller A och D och tryck mellanslag för att titta. På en pekskärm trycker du där du vill titta.',
  movieHint: 'Titta efter något som sticker fram – en filtflik eller ett nalleöra!',
  movieStart: 'Börja leta', toSofa: 'TILL SOFFAN', foundItem: '{name} hittad! Bär den till soffan.',
  placedItem: '{name} ligger i soffan. {n} kvar.', placedLast: '{name} ligger i soffan. Allt är klart!', filmStarts: 'Nu börjar filmen!',
  movieDone: 'Filmen börjar!', movieDoneBody: 'Vilken mysig soffa, Carl-Otto! Nu är det filmkväll.', lookAgain: 'Leta igen',
  moviePaused: 'Paus i filmkvällen', moviePausedBody: 'Allt ligger kvar där det är.',
  homeTitle: 'Hemma', homeBlurb: 'Ett litet spel i varje rum – från hemkomst till godnatt.', homeStart: 'Gå in',
  houseTitle: 'Hemma hos Carl-Otto', houseIntro: 'Tryck på ett rum!', toMap: 'Till kartan', play: 'Spela', soon: 'Kommer snart',
  doneMark: 'KLAR!', eveningTag: 'IKVÄLL', morningTag: 'NÄSTA MORGON', suggestion: 'FÖRSLAG: {title}',
  eveningDone: 'Kvällen är klar – sov gott!', houseKeys: 'VÄLJ RUM ◀ ▶     ENTER · SPELA     ESC · TILLBAKA     M · LJUD',
  craftTitle: 'Pysselhörnan', crayonWord: 'krita', toolCrayon: 'Krita', toolBucket: 'Hink', toolEraser: 'Sudd',
  sizeThin: 'Tunn', sizeMid: 'Mellan', sizeThick: 'Tjock', undo: 'Ångra', newPaper: 'Nytt papper', hang: 'Sätt upp!',
  choosePaper: 'Vad vill du rita på?', blankPaper: 'Tomt papper', keepDrawing: 'Fortsätt rita', hungTitle: 'Uppsatt!',
  hungBody: 'Vilken fin bild, Carl-Otto! Nu hänger den på väggen i vardagsrummet.', drawMore: 'Rita en till',
  nothingYet: 'Rita något först!',
  craftKeys: 'Tangenter: pilarna flyttar pennan, mellanslag ritar, 1–0 väljer färg, B byter pensel, S spegel, Z ångrar, P spela, N nytt papper, G mina bilder. Med ett klistermärke valt: pilarna flyttar det, + och − ändrar storleken, Delete slänger det.',
  actSponge: 'Svamp – gnid över pappret för att sudda allt', actUndo: 'Ångra', actNew: 'Nytt papper', actGallery: 'Mina bilder',
  actPlay: 'Spela – bilden blir levande', actStop: 'Stoppa', actHang: 'Sätt upp bilden', symOff: 'Spegel av', symOn: 'Spegel: {n} delar',
  pageFamily: 'Familjen och kompisarna', pageThings: 'Saker', pageShapes: 'Former', nextPage: 'Nästa sida',
  stickerBigger: 'Större', stickerSmaller: 'Mindre', stickerBin: 'Släng klistermärket', galleryTitle: 'Mina bilder',
  hangLiving: 'Häng i vardagsrummet', hangHall: 'Häng i hallen', hangBedroom: 'Häng i mitt rum', galleryBin: 'Släng bilden',
  galleryBack: 'Tillbaka till pappret', pictureWord: 'Bild', wiped: 'Rent papper!', letterDone: 'Bra skrivet!',
  nameDone: 'Du skrev ditt namn!', hungWhere: 'Bilden hänger nu i {room}.', roomLiving: 'vardagsrummet', roomHall: 'hallen', roomBedroom: 'ditt rum',
  pancakeTitle: 'Pannkakor', whiskIt: 'Vispa', pourIt: 'Häll i!', flipIt: 'Vänd!', toPlate: 'Till tallriken!', waitIt: 'Vänta…',
  toppingOn: 'Lägg på', pancakeDoneBtn: 'Klart!', pancakeDone: 'Pannkakorna är klara!',
  pancakeDoneBody: 'Mums, Carl-Otto! Fem goda pannkakor. Smaklig måltid!', bakeAgain: 'Baka igen', waterPlant: 'Vattna blomman',
  pancakeKeys: 'MELLANSLAG · NÄSTA STEG     PILAR · VISPA     1–5 · PÅLÄGG     Z · ÅNGRA     ESC · KARTAN',
  goodnightTitle: 'Godnatt', putAway: 'lägg på plats', bedLabel: 'Sängen', lampLabel: 'Lampan', pianoLabel: 'Pianot',
  playAlong: 'Spela med', freePlay: 'Spela fritt', closePiano: 'Stäng pianot', goodnightDone: 'Sov gott, Carl-Otto!',
  goodnightDoneBody: 'Leksakerna är på plats, djuren sover och lampan är släckt. Godnatt!', goodnightAgain: 'En gång till',
  goodnightKeys: 'MELLANSLAG · NÄSTA     P · PIANOT     1–8 · TONER     ESC · KARTAN',
  morningTitle: 'God morgon', openCurtains: 'Dra isär gardinerna', tickleFoot: 'Kittla pappas fot', teddyNose: 'Nallen på mammas näsa',
  jumpOnBed: 'Hoppa i sängen', morningDone: 'God morgon, Carl-Otto!',
  morningDoneBody: 'Alla lampor lyser och alla är vakna. Hjälmen på – nu cyklar vi till förskolan!', toPreschool: 'Dags för förskolan!',
  morningKeys: 'MELLANSLAG · NÄSTA / HOPPA     ESC · KARTAN',
  homecomingTitle: 'Hemkomst', homecomingDone: 'Välkommen hem!',
  homecomingDoneBody: 'Skorna står i par, jackan hänger på kroken och hjälmen ligger på hyllan.', toCraft: 'Till pysselhörnan',
  homecomingKeys: 'MELLANSLAG · NÄSTA     ESC · KARTAN',
  diningTitle: 'Duka bordet', lightCandles: 'Tänd ett ljus', serveFood: 'Bär in maten', diningDone: 'Tack för maten!',
  diningDoneBody: 'Fint dukat och gott ätet. Nu är det snart filmkväll i vardagsrummet!', toMovie: 'Till filmkvällen',
  bathTitle: 'Tänder och tvål', bathStool: 'Kliv upp på pallen', bathPump: 'Pumpa tvål', bathRub: 'Gnugga händerna',
  bathTap: 'Sätt på kranen', bathTowel: 'Torka händerna', bathTube: 'Tandkräm på borsten', bathBrush: 'Borsta tänderna',
  bathCup: 'Skölj munnen', bathDone: 'Rena tänder!', bathDoneBody: 'Rena händer och blanka tänder. Nu är det läggdags!', toBed: 'Till sängen',
  sillyTitle: 'Fånig i spegeln', sillyFace: 'Ny min', sillyPhoto: 'Ta kort!', sillyClear: 'Ta av allt', sillyOff: 'av',
};

const en: Record<keyof typeof sv, string> = {
  collection: 'GAMES FROM RINGSTORP', choose: 'What shall we play?', intro: 'Two worlds. New adventures just around the corner.',
  ringstorp: 'Ringstorp Run', runTag: 'ARCADE ADVENTURES · 4 LEVELS',
  runDescription: 'Parcels, secret assignments and a long run through Karlstad. Take the yellow bus home to Liljedal.', runAction: 'Choose a level',
  carl: 'Carl-Ottos spel', carlTag: 'LITTLE ADVENTURES · BIG CURIOSITY',
  carlDescription: 'Blue helmet on! Ride to preschool, play hide and seek with friends, and get ready for movie night at home.', carlAction: 'Explore the games',
  back: 'All games', first: 'GAME 1', bikeTitle: 'Off to preschool',
  bikeDescription: 'It’s a lovely morning in Höganäs. Help Carl-Otto cycle to the red preschool and dodge the apples falling from the trees.',
  bikeInstructions: 'The bike rolls along by itself. Steer with the arrow keys or WASD. On a touchscreen, use the arrow buttons.',
  bikeHint: 'Watch the rings on the ground – that’s where the next apple will fall!',
  start: 'Start cycling', pause: 'Pause', resume: 'Keep cycling', again: 'Ride again',
  paused: 'A little break', pausedBody: 'Your bike will wait here until you’re ready.',
  won: 'You made it to preschool!', wonBody: 'Well done, Carl-Otto! Park your bike – a day of play is waiting.',
  lost: 'Oops, an apple!', lostBody: 'Let’s try another ride! Watch the rings on the ground and steer clear.',
  home: 'Home', preschool: 'Preschool', left: 'm left', hearts: 'Hearts', avoided: 'apples avoided',
  steer: 'STEER', pauseHint: 'ESC · PAUSE     M · SOUND', soundOn: 'Sound: on', soundOff: 'Sound: off', up: 'Steer up', down: 'Steer down', moveLeft: 'Steer left', moveRight: 'Steer right',
  footer: 'LITTLE ADVENTURES IN HELSINGBORG, HÖGANÄS AND KARLSTAD', menu: 'Choose a game',
  second: 'GAME 2', hideTitle: 'Hide and seek',
  bikeBlurb: 'Ride to preschool and dodge the falling apples.', hideBlurb: 'Find all five friends in the preschool yard.',
  hideDescription: 'The friends are hiding in the preschool yard. Can Carl-Otto find all five? They’re not very good at hiding…',
  hideInstructions: 'Walk with the arrow keys or A and D. Press space at a hiding place to look. On a touchscreen, tap where you want to look.',
  hideHint: 'Listen for giggles – and look out for feet sticking out!',
  countStart: 'Start counting', skipCount: 'SPACE · STOP COUNTING', here: 'Ready or not, here I come!', look: 'Look!', hihi: 'hee hee!',
  foundAll: 'You found everyone!', foundAllBody: 'All the friends are found. Great seeking, Carl-Otto!', tookTime: 'It took {time}.',
  seekAgain: 'Play again', foundStatus: '{name} found! {n} to go.', foundLast: '{name} found! Everyone is found!',
  friends: 'FRIENDS', seekKeys: 'WALK ◀ ▶ / A D     LOOK · SPACE     ESC · PAUSE     M · SOUND', hidePaused: 'A little break',
  hidePausedBody: 'Your friends are waiting in their hiding places.',
  third: 'GAME 3', movieTitle: 'Movie night', movieBlurb: 'Find what movie night needs and make the sofa cosy.',
  movieInstructions: 'It’s movie night! Find the blanket, the cushion, Teddy, the popcorn and the remote, and carry them to the sofa. Walk with the arrow keys or A and D, and press space to look. On a touchscreen, tap where you want to look.',
  movieHint: 'Look out for something poking out – a corner of the blanket or a teddy ear!',
  movieStart: 'Start looking', toSofa: 'FOR THE SOFA', foundItem: 'Found {name}! Carry it to the sofa.',
  placedItem: 'On the sofa: {name}. {n} to go.', placedLast: 'On the sofa: {name}. Everything’s ready!', filmStarts: 'The film is starting!',
  movieDone: 'The film is on!', movieDoneBody: 'What a cosy sofa, Carl-Otto! Movie night can begin.', lookAgain: 'Play again',
  moviePaused: 'A little break', moviePausedBody: 'Everything stays right where it is.',
  homeTitle: 'At home', homeBlurb: 'A little game in every room – from coming home to goodnight.', homeStart: 'Go inside',
  houseTitle: 'At Carl-Otto’s house', houseIntro: 'Tap a room!', toMap: 'To the map', play: 'Play', soon: 'Coming soon',
  doneMark: 'DONE!', eveningTag: 'THIS EVENING', morningTag: 'NEXT MORNING', suggestion: 'NEXT UP: {title}',
  eveningDone: 'The evening is done – sleep tight!', houseKeys: 'CHOOSE ROOM ◀ ▶     ENTER · PLAY     ESC · BACK     M · SOUND',
  craftTitle: 'The craft corner', crayonWord: 'crayon', toolCrayon: 'Crayon', toolBucket: 'Bucket', toolEraser: 'Eraser',
  sizeThin: 'Thin', sizeMid: 'Medium', sizeThick: 'Thick', undo: 'Undo', newPaper: 'New paper', hang: 'Put it up!',
  choosePaper: 'What shall we draw on?', blankPaper: 'Plain paper', keepDrawing: 'Keep drawing', hungTitle: 'Up on the wall!',
  hungBody: 'What a lovely picture, Carl-Otto! It’s hanging on the living room wall now.', drawMore: 'Draw another',
  nothingYet: 'Draw something first!',
  craftKeys: 'Keys: the arrows move the pen, space draws, 1–0 choose a colour, B changes brush, S mirror, Z undo, P play, N new paper, G my pictures. With a sticker chosen: the arrows move it, + and − change its size, Delete throws it away.',
  actSponge: 'Sponge – rub over the paper to wipe it all', actUndo: 'Undo', actNew: 'New paper', actGallery: 'My pictures',
  actPlay: 'Play – the picture comes alive', actStop: 'Stop', actHang: 'Put the picture up', symOff: 'Mirror off', symOn: 'Mirror: {n} parts',
  pageFamily: 'Family and friends', pageThings: 'Things', pageShapes: 'Shapes', nextPage: 'Next page',
  stickerBigger: 'Bigger', stickerSmaller: 'Smaller', stickerBin: 'Throw the sticker away', galleryTitle: 'My pictures',
  hangLiving: 'Hang in the living room', hangHall: 'Hang in the hall', hangBedroom: 'Hang in my room', galleryBin: 'Throw the picture away',
  galleryBack: 'Back to the paper', pictureWord: 'Picture', wiped: 'Clean paper!', letterDone: 'Well written!',
  nameDone: 'You wrote your name!', hungWhere: 'The picture now hangs in {room}.', roomLiving: 'the living room', roomHall: 'the hall', roomBedroom: 'your room',
  pancakeTitle: 'Pancakes', whiskIt: 'Whisk', pourIt: 'Pour!', flipIt: 'Flip!', toPlate: 'Onto the plate!', waitIt: 'Wait…',
  toppingOn: 'Put on', pancakeDoneBtn: 'Done!', pancakeDone: 'The pancakes are ready!',
  pancakeDoneBody: 'Yummy, Carl-Otto! Five lovely pancakes. Enjoy your meal!', bakeAgain: 'Bake again', waterPlant: 'Water the plant',
  pancakeKeys: 'SPACE · NEXT STEP     ARROWS · WHISK     1–5 · TOPPING     Z · UNDO     ESC · MAP',
  goodnightTitle: 'Goodnight', putAway: 'put away', bedLabel: 'The bed', lampLabel: 'The lamp', pianoLabel: 'The piano',
  playAlong: 'Play along', freePlay: 'Play freely', closePiano: 'Close the piano', goodnightDone: 'Sleep tight, Carl-Otto!',
  goodnightDoneBody: 'The toys are put away, the animals are asleep and the lamp is off. Goodnight!', goodnightAgain: 'Once more',
  goodnightKeys: 'SPACE · NEXT     P · PIANO     1–8 · NOTES     ESC · MAP',
  morningTitle: 'Good morning', openCurtains: 'Open the curtains', tickleFoot: 'Tickle Pappa’s foot', teddyNose: 'Teddy on Mamma’s nose',
  jumpOnBed: 'Bounce on the bed', morningDone: 'Good morning, Carl-Otto!',
  morningDoneBody: 'All the bulbs are lit and everyone is awake. Helmet on – let’s cycle to preschool!', toPreschool: 'Off to preschool!',
  morningKeys: 'SPACE · NEXT / BOUNCE     ESC · MAP',
  homecomingTitle: 'Home again', homecomingDone: 'Welcome home!',
  homecomingDoneBody: 'The shoes stand in pairs, the jacket hangs on its hook and the helmet is on the shelf.', toCraft: 'To the craft corner',
  homecomingKeys: 'SPACE · NEXT     ESC · MAP',
  diningTitle: 'Set the table', lightCandles: 'Light a candle', serveFood: 'Bring in the food', diningDone: 'Thank you for the food!',
  diningDoneBody: 'Nicely set and nicely eaten. Movie night in the living room is next!', toMovie: 'To movie night',
  bathTitle: 'Teeth and soap', bathStool: 'Step up on the stool', bathPump: 'Pump the soap', bathRub: 'Rub your hands',
  bathTap: 'Turn on the tap', bathTowel: 'Dry your hands', bathTube: 'Toothpaste on the brush', bathBrush: 'Brush your teeth',
  bathCup: 'Rinse your mouth', bathDone: 'Clean teeth!', bathDoneBody: 'Clean hands and shiny teeth. Now it’s bedtime!', toBed: 'To bed',
  sillyTitle: 'Silly in the mirror', sillyFace: 'New face', sillyPhoto: 'Take a photo!', sillyClear: 'Take it all off', sillyOff: 'off',
};

export const familyText = (key: keyof typeof sv): string => (getLang() === 'sv' ? sv : en)[key];
